[build]
builder = "NIXPACKS"

[deploy]
releaseCommand = "python manage.py collectstatic --noinput && python manage.py migrate"
startCommand = "gunicorn unimentor.wsgi"
healthcheckPath = "/"
healthcheckTimeout = 120

[environments]
  [environments.production]
    ALLOWED_HOSTS = "unicraft.uz,unicraft-production.up.railway.app"
    CORS_ALLOWED_ORIGINS = "https://unicraft.uz"
    CSRF_TRUSTED_ORIGINS = "https://unicraft.uz,https://unicraft-production.up.railway.app"
    DEBUG = "False"
    FRONTEND_URL = "https://unicraft.uz"
    PUBLIC_BACKEND_URL = "https://unicraft-production.up.railway.app"
