[build]
builder = "NIXPACKS"

[deploy]
releaseCommand = "python manage.py collectstatic --noinput && python manage.py migrate"
startCommand = "gunicorn unimentor.wsgi"
healthcheckPath = "/"
healthcheckTimeout = 120


