# Generated by Django 5.2.5 on 2025-09-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=255)),
                ('program', models.CharField(blank=True, max_length=255)),
                ('achievements', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated list', max_length=255)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('availability', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_document_url', models.URLField(blank=True)),
            ],
        ),
    ]
