# Generated by Django 5.2.5 on 2025-09-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='year',
            field=models.IntegerField(blank=True, help_text='Study year or graduation year', null=True),
        ),
    ]
