
# Generated by Django 5.2.5 on 2025-09-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentorprofile_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='price_per_hour',
        ),
    ]
