# Generated by Django 5.2.5 on 2025-09-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_remove_mentorprofile_price_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
